
export const housesData = [
  {
    id: 1,
    type: 'House',
    name: 'House 1',
    title:"Palm Harbor",
    image:'img/houses/house1.png',
    country: 'United States',
    address: '7240C Argyle St. Lawndale, CA 90260',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    date: '01 Aug 2022',
    price: '110000',
  },
  {
    id: 2,
    type: 'House',
    name: 'House 2',
    title:"Beverly Springfield",
    image: "img/houses/house2.png",
    country: 'Canada',
    address: '798 Talbot St. Bridgewater, NJ 08807',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    date: '10 Aug 2022',
    price: '140000',
  },
  {
    id: 3,
    type: 'House',
    name: 'House 3',
    title:"Faulkner Ave",
    image: "img/houses/house3.png",
    country: 'United States',
    address: '2 Glen Creek St. Alexandria, VA 22304',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    date: '25 Aug 2022',
    price: '170000',
  },
  {
    id: 4,
    type: 'House',
    name: 'House 4',
    title:"Robins Hedge ",
    image: "img/houses/house4.png",
    country: 'Canada',
    address: '84 Woodland St. Cocoa, FL 32927',
    bedrooms: '6',
    bathrooms: '3',
    surface: '4200 sq ft',
    date: '25/08/2022',
    price: '200000',
  },
  {
    id: 5,
    type: 'House',
    name: 'House 5',
    title:"Little Copse ",
    image: "img/houses/house5.png",
    country: 'United States',
    address: '28 Westport Dr. Warminster, PA 18974',
    bedrooms: '5',
    bathrooms: '3',
    surface: '4200 sq ft',
    date: '29/08/2022',
    price: '210000',
  },
  {
    id: 6,
    type: 'House',
    name: 'House 6',
    title:"Jackdaws ",
    image: "img/houses/house6.png",
    country: 'Canada',
    address: '32 Pawnee Street Butte, MT 59701',
    bedrooms: '6',
    bathrooms: '3',
    surface: '6200 sq ft',
    date: '05/09/2022',
    price: '220000',
  },
  {
    id: 7,
    type: 'Apartament',
    name: 'Apartament 1',
    title:"Wisteria Cottages ",
    image: "img/apartments/a1.png",
    country: 'Canada',
    address: '32 Pawnee Street Butte, MT 59701',
    bedrooms: '2',
    bathrooms: '1',
    surface: '1200 sq ft',
    date: '10/09/2022',
    price: '20000',
  },
  {
    id: 8,
    type: 'Apartament',
    name: 'Apartament 2',
    title:"Mighty Oaks ",
    image: "img/apartments/a2.png",
    country: 'United States',
    address: '28 Westport Dr. Warminster, PA 18974',
    bedrooms: '3',
    bathrooms: '1',
    surface: '1000 sq ft',
    date: '18/09/2022',
    price: '30000',
  },
  {
    id: 9,
    type: 'Apartament',
    name: 'Apartament 3',
    title:"The Burrow ",
    image: "img/apartments/a3.png",
    country: 'United States',
    address: '84 Woodland St. Cocoa, FL 32927',
    bedrooms: '2',
    bathrooms: '1',
    surface: '1100 sq ft',
    date: '24/09/2022',
    price: '40000',
  },
  {
    id: 10,
    type: 'House',
    name: 'House 7',
    title:"The Gables ",
    image: "img/houses/house7.png",
    country: 'Canada',
    address: '7240C Argyle St. Lawndale, CA 90260',
    bedrooms: '5',
    bathrooms: '3',
    surface: '3200 sq ft',
    date: '30/09/2022',
    price: '117000',
  },
  {
    id: 11,
    type: 'House',
    name: 'House 8',
    title:"Orchard House ",
    image: "img/houses/house8.png",
    country: 'Canada',
    address: '798 Talbot St. Bridgewater, NJ 08807',
    bedrooms: '7',
    bathrooms: '2',
    surface: '2200 sq ft',
    date: '05/10/2022',
    price: '145000',
  },
  {
    id: 12,
    type: 'House',
    name: 'House 9',
    title:"Meadow View ",
    image: "img/houses/house9.png",
    country: 'United States',
    address: '2 Glen Creek St. Alexandria, VA 22304',
    bedrooms: '4',
    bathrooms: '4',
    surface: '4600 sq ft',
    date: '14/10/2022',
    price: '139000',
  },
  {
    id: 13,
    type: 'House',
    name: 'House 10',
    title:"The Hollies ",
    image: "img/houses/house10.png",
    country: 'Canada',
    address: '84 Woodland St. Cocoa, FL 32927',
    bedrooms: '5',
    bathrooms: '2',
    surface: '5200 sq ft',
    date: '22/10/2022',
    price: '180000',
  },
  {
    id: 14,
    type: 'House',
    name: 'House 11',
    title:"The Willows ",
    image: "img/houses/house11.png",
    country: 'United States',
    address: '28 Westport Dr. Warminster, PA 18974',
    bedrooms: '5',
    bathrooms: '2',
    surface: '3200 sq ft',
    date: '27/10/2022',
    price: '213000',
  },
  {
    id: 15,
    type: 'House',
    name: 'House 12',
    title:"The Barn ",
    image: "img/houses/house12.png",
    country: 'Canada',
    address: '32 Pawnee Street Butte, MT 59701',
    bedrooms: '4',
    bathrooms: '3',
    surface: '5200 sq ft',
    date: '1/11/2022',
    price: '221000',
  },
  {
    id: 16,
    type: 'Apartament',
    name: 'Apartament 16',
    title:"Lilac Cottage ",
    image: "img/apartments/a4.png",
    country: 'Canada',
    address: '32 Pawnee Street Butte, MT 59701',
    bedrooms: '2',
    bathrooms: '1',
    surface: '1300 sq ft',
    date: '07/11/2022',
    price: '21000',
  },
  {
    id: 17,
    type: 'Apartament',
    name: 'Apartament 17',
    title:" Primrose Cottage",
    image: "img/apartments/a5.png",
    country: 'United States',
    address: '28 Westport Dr. Warminster, PA 18974',
    bedrooms: '3',
    bathrooms: '1',
    surface: '1000 sq ft',
    date: '14/11/2022',
    price: '32000',
  },
  {
    id: 18,
    type: 'Apartament',
    name: 'Apartament 18',
    title:"Primrose Cottage ",
    image: "img/apartments/a6.png",
    country: 'Canada',
    address: '84 Woodland St. Cocoa, FL 32927',
    bedrooms: '3',
    bathrooms: '1',
    surface: '1200 sq ft',
    date: '23/11/2022',
    price: '38000',
  },
];
